import {
  Code2,
  Search,
  Settings,
  Megaphone,
  Monitor,
  Smartphone,
  Palette,
  MapPin,
  ClipboardList,
  PenTool,
  ShieldCheck,
  RefreshCw,
  Zap,
  Layout,
  TrendingUp,
  FileCode,
  Gauge,
} from 'lucide-react';

export const COMPANY = {
  name: 'Zenith Web Solutions',
  tagline: 'Helping Businesses Build, Rank & Grow.',
  email: 'hello@zenithwebsolutions.com',
  phone: '+1 (555) 123-4567',
  address: '123 Innovation Drive, Suite 200, Austin, TX 78701',
  hours: 'Mon – Fri: 9:00 AM – 6:00 PM (CST)',
};

export const NAV_LINKS = [
  { label: 'Home', path: '/' },
  { label: 'Services', path: '/services' },
  { label: 'About', path: '/about' },
  { label: 'Portfolio', path: '/portfolio' },
  { label: 'Process', path: '/process' },
  { label: 'Pricing', path: '/pricing' },
  { label: 'FAQ', path: '/faqs' },
  { label: 'Contact', path: '/contact' },
];

export const SERVICES = [
  {
    id: 'website-design',
    title: 'Website Design',
    icon: Palette,
    short: 'Custom, high-fidelity UI/UX mockups designed to reflect absolute brand credibility and maximize visitor conversions.',
    overview: 'Our website design process focuses on establishing trust immediately. We build visual systems that project authority and structure navigation to guide visitors toward your calls to action.',
    benefits: ['High-fidelity interactive prototype mockups', 'Systemized light-mode color architectures', 'Slick, readable grid layouts', 'Optimized visual hierarchies to engage visitors'],
    included: ['Custom Figma designs', 'Creative direction discovery', 'Interactive layout prototyping', 'Brand typography integration'],
    whyUs: 'We reject generic design templates. Every page grid, margin, and typography scale is crafted from the ground up to represent absolute quality.',
  },
  {
    id: 'website-development',
    title: 'Website Development',
    icon: Code2,
    short: 'Hyper-performant React and Vite web applications utilizing clean code structures and layout speed optimizations.',
    overview: 'We compile web assets with strict developer standards. Clean code blocks, component architectures, and lightweight assets ensure your website loads instantly.',
    benefits: ['Sub-second page loading speeds', 'Clean, componentized React codebases', 'Universal mobile-responsive styling', 'Search engine accessible code structure'],
    included: ['Vite & React workspace setup', 'Component bundle size checks', 'Custom database integrations', 'Domain server setups'],
    whyUs: 'Our developers build clean, modern codebases to ensure your platform loads quickly on all networks.',
  },
  {
    id: 'local-seo',
    title: 'Local SEO',
    icon: MapPin,
    short: 'Improve regional search presence to help local business offices secure first-page Google Map Pack placements.',
    overview: 'We align local search query setups, schema mappings, and map pack indexes to bring local business offices to the top of Google results.',
    benefits: ['First-page Map Pack ranking focus', 'Geographically-targeted organic leads', 'Enhanced phone inquiry metrics', 'Optimized review acquisition blueprints'],
    included: ['Local keyword mapping audits', 'Structured Schema JSON-LD injects', 'Local citation sync setups', 'Competitor query analysis charts'],
    whyUs: 'We implement advanced localized keyword queries that ensure you appear when high-intent local clients search.',
  },
  {
    id: 'technical-seo',
    title: 'Technical SEO',
    icon: Settings,
    short: 'Optimize site sitemaps, indexing structures, and crawl speeds to help search engine crawlers rank pages correctly.',
    overview: 'Technical SEO ensures your website meets the technical requirements of search engines for improved crawling, indexing, and ranking. We identify and fix issues that may be holding your site back.',
    benefits: ['Improved crawlability', 'Faster page load times', 'Better indexing', 'Enhanced site architecture', 'Structured data implementation'],
    included: ['Technical audit', 'Site speed optimization', 'Schema markup', 'XML sitemap optimization', 'Robots.txt configuration'],
    whyUs: 'Our technical SEO expertise helps ensure your website has a strong foundation that supports all your other digital marketing efforts.',
  },
  {
    id: 'digital-marketing',
    title: 'Digital Marketing',
    icon: Megaphone,
    short: 'Conversion-focused digital marketing campaigns targeting search engines and high-intent audiences.',
    overview: 'Our digital marketing services help businesses reach their target audience through strategic online campaigns. We create and manage campaigns that drive traffic, generate leads, and increase conversions.',
    benefits: ['Targeted audience reach', 'Measurable results', 'Multi-channel strategies', 'Data-driven optimization', 'Increased brand visibility'],
    included: ['Marketing strategy development', 'Campaign management', 'Performance tracking', 'Monthly reporting', 'Ongoing optimization'],
    whyUs: 'We take a data-driven approach to digital marketing, ensuring every dollar spent contributes to your business growth.',
  },
  {
    id: 'software-development',
    title: 'Software Development',
    icon: Monitor,
    short: 'Custom full-stack web software, dashboard builders, and SaaS portals designed to automate processes.',
    overview: 'We engineer complex internal software tools and SaaS platforms with secure, scalable databases and custom APIs.',
    benefits: ['Custom automation of company tasks', 'Highly secure database storage layouts', 'Custom API integration architectures', 'Zero dependency bloat frameworks'],
    included: ['Full-stack database planning', 'User role authorization systems', 'External API connections', 'Rigorous security pen-testing'],
    whyUs: 'We build tailored software tools that fit your business workflow, eliminating unnecessary administrative steps.',
  },
  {
    id: 'mobile-app-development',
    title: 'Mobile App Development',
    icon: Smartphone,
    short: 'Responsive, fast iOS and Android mobile app development for businesses seeking mobile client tools.',
    overview: 'We create mobile applications for iOS and Android that provide seamless user experiences. Whether you need a native app or a cross-platform solution, we deliver quality mobile products.',
    benefits: ['Cross-platform compatibility', 'Intuitive user interface', 'Performance optimized', 'Push notification support', 'App store optimization'],
    included: ['UI/UX design', 'App development', 'API integration', 'Testing across devices', 'App store submission'],
    whyUs: 'We build mobile apps that users enjoy using, with a focus on performance, usability, and meeting real business objectives.',
  },
  {
    id: 'graphic-design',
    title: 'Graphic Design',
    icon: PenTool,
    short: 'Premium digital branding guides, vector logo kits, and layouts representing authority.',
    overview: 'Our graphic design services help businesses create a strong visual identity. From logos to marketing materials, we design assets that communicate your brand message effectively.',
    benefits: ['Professional brand identity', 'Consistent visual language', 'Print and digital assets', 'Marketing material design', 'Social media graphics'],
    included: ['Logo design', 'Brand guidelines', 'Marketing collateral', 'Social media templates', 'Presentation design'],
    whyUs: 'Our designers create visual assets that are not only aesthetically pleasing but also strategically aligned with your business goals.',
  },
  {
    id: 'gbp-optimization',
    title: 'Google Business Profile Optimization',
    icon: Search,
    short: 'Complete auditing, keyword alignments, and listings cleanup to improve map index positioning.',
    overview: 'A well-optimized Google Business Profile is essential for local visibility. We optimize every aspect of your profile to help you stand out in local search results and Google Maps.',
    benefits: ['Higher Map Pack rankings', 'Improved local visibility', 'More customer inquiries', 'Better first impressions', 'Enhanced trust signals'],
    included: ['Profile audit', 'Category optimization', 'Description and services setup', 'Photo optimization', 'Q&A management'],
    whyUs: 'We stay current with Google\'s evolving guidelines to ensure your profile is optimized for maximum visibility and engagement.',
  },
  {
    id: 'gbp-management',
    title: 'Google Business Profile Management',
    icon: ClipboardList,
    short: 'Continuous optimization, review responses tracking, and listings health check monitoring.',
    overview: 'Consistent management of your Google Business Profile keeps your business information accurate and your profile active. We handle regular updates, posts, and review management.',
    benefits: ['Consistent profile activity', 'Accurate business information', 'Regular engagement', 'Review monitoring', 'Performance tracking'],
    included: ['Weekly profile updates', 'Review response management', 'Monthly performance reports', 'Information accuracy checks', 'Competitive monitoring'],
    whyUs: 'We treat your Google Business Profile as a living asset, continuously optimizing it to maintain and improve your local search performance.',
  },
  {
    id: 'gbp-posting',
    title: 'Google Business Profile Posting',
    icon: Layout,
    short: 'Engaging updates, promotions, and services announcements posted to retain active signals.',
    overview: 'Regular posting on your Google Business Profile keeps your audience engaged and signals to Google that your business is active. We create and publish relevant posts consistently.',
    benefits: ['Increased profile engagement', 'Fresh content signals', 'Promotional opportunities', 'Event announcements', 'Improved local rankings'],
    included: ['Content planning', 'Post creation', 'Image optimization', 'Scheduling and publishing', 'Performance tracking'],
    whyUs: 'We create strategic, engaging posts that keep your profile active and provide value to potential customers finding your business online.',
  },
  {
    id: 'gbp-reinstatement',
    title: 'Google Business Profile Reinstatement',
    icon: ShieldCheck,
    short: 'Appealing suspended or disabled Google Business listings to restore search footprint.',
    overview: 'If your Google Business Profile has been suspended or disabled, our team can help navigate the reinstatement process. We understand Google\'s policies and work to restore your profile efficiently.',
    benefits: ['Expert reinstatement process', 'Policy compliance review', 'Profile recovery', 'Prevention strategies', 'Ongoing compliance'],
    included: ['Suspension analysis', 'Compliance review', 'Reinstatement application', 'Follow-up communication', 'Preventive recommendations'],
    whyUs: 'We have experience navigating Google\'s reinstatement process and understand what it takes to get your profile back up and running.',
  },
  {
    id: 'website-maintenance',
    title: 'Website Maintenance',
    icon: RefreshCw,
    short: 'Monthly security upgrades, backups setup, link checking, and platform diagnostic tests.',
    overview: 'Regular website maintenance ensures your site stays secure, up-to-date, and performing optimally. We handle updates, backups, security monitoring, and content changes so you can focus on your business.',
    benefits: ['Regular security updates', 'Performance monitoring', 'Content updates', 'Backup management', 'Uptime monitoring'],
    included: ['Software updates', 'Security patches', 'Daily backups', 'Performance checks', 'Monthly reports'],
    whyUs: 'We provide reliable, consistent maintenance so your website remains a strong business asset long after launch.',
  },
  {
    id: 'website-speed-optimization',
    title: 'Website Speed Optimization',
    icon: Zap,
    short: 'Diagnose sitemaps, script sizes, and image compressions to achieve high speed scores.',
    overview: 'Website speed directly impacts user experience and search rankings. We analyze and optimize every aspect of your site to achieve the fastest possible load times.',
    benefits: ['Faster page load times', 'Better user experience', 'Improved search rankings', 'Lower bounce rates', 'Higher conversion rates'],
    included: ['Speed audit', 'Image optimization', 'Code minification', 'Caching setup', 'CDN configuration'],
    whyUs: 'We use a systematic approach to speed optimization, addressing every factor that contributes to slow load times.',
  },
  {
    id: 'landing-page-design',
    title: 'Landing Pages',
    icon: FileCode,
    short: 'High-converting layout mockups and single-page applications optimized for ad lead capture.',
    overview: 'Our landing pages are designed with one goal: conversions. We create focused, compelling pages that guide visitors toward taking action, whether that\'s filling out a form, making a call, or completing a purchase.',
    benefits: ['Conversion-focused design', 'A/B testing ready', 'Fast loading', 'Mobile optimized', 'Clear call-to-action'],
    included: ['Landing page design', 'Copywriting assistance', 'Form integration', 'Analytics setup', 'Performance tracking'],
    whyUs: 'We design landing pages based on proven conversion principles, ensuring every element on the page serves a strategic purpose.',
  },
  {
    id: 'website-redesign',
    title: 'Website Redesign',
    icon: TrendingUp,
    short: 'Preserve sitemap index value while fully updating layouts, layouts grid, and responsiveness.',
    overview: 'If your current website is outdated, slow, or not generating results, a redesign can transform your digital presence. We modernize your site while preserving your SEO equity and brand identity.',
    benefits: ['Modern, updated design', 'Improved performance', 'Better user experience', 'SEO preservation', 'Mobile responsiveness'],
    included: ['Current site audit', 'New design concepts', 'Content migration', 'SEO redirect mapping', 'Launch and testing'],
    whyUs: 'We approach redesigns strategically, ensuring your new site looks great, performs well, and preserves the search rankings you\'ve built.',
  },
];

export const PROCESS_STEPS = [
  {
    step: 1,
    title: 'Free Consultation',
    description: 'We align on business goals, technical requirements, and branding details to define the project scope.',
  },
  {
    step: 2,
    title: 'Requirement Analysis',
    description: 'We document features, target keywords, and visual inspiration to create a clear project roadmap.',
  },
  {
    step: 3,
    title: 'Planning & Strategy',
    description: 'We audit competitor sites and analyze local search terms to position your brand for growth.',
  },
  {
    step: 4,
    title: 'UI/UX Visual Design',
    description: 'We create high-end visual mockups in Figma, focusing on clean typography and elegant spacing.',
  },
  {
    step: 5,
    title: 'Full Stack Development',
    description: 'Our developers build your design using clean, efficient code, ensuring fast load times and responsiveness.',
  },
  {
    step: 6,
    title: 'Quality Testing & QA',
    description: 'We run audits across browsers and devices to check code quality and link performance before launch.',
  },
  {
    step: 7,
    title: 'SEO Optimization',
    description: 'We set up schema tags, verify sitemaps, and optimize site speed to prepare your site for search visibility.',
  },
  {
    step: 8,
    title: 'Server Deployment',
    description: 'We handle sitemap submission, configure domain servers, and verify SSL security to launch your site.',
  },
  {
    step: 9,
    title: 'Ongoing Support',
    description: 'We provide regular updates, database backups, and performance monitoring to keep your site running smoothly.',
  },
];

export const PORTFOLIO_CATEGORIES = [
  'All',
  'Plumbing',
  'Roofing',
  'Interior Design',
  'Restaurant',
  'Dental',
  'Construction',
  'Law Firm',
  'HVAC',
  'Landscaping',
];

export const PORTFOLIO_PROJECTS = [
  {
    id: 1,
    category: 'Plumbing',
    industry: 'Plumbing',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'A premium booking and dispatch portal concept designed for plumbing contractors. Features real-time appointment booking, service pricing transparency, and localized SEO schema mapping to drive direct regional service calls.',
    challenge: 'Local commercial contractors often struggle with dated, template-style landing pages that do not establish professional authority. The goal was to build a clean web application that manages bookings and establishes local credibility.',
    solution: 'We engineered a modern portal with clear appointment scheduling tools, service area highlights, and custom schema mapping to support local search visibility.',
    outcome: 'Built a responsive layout that simplifies the booking process, with optimized asset delivery resulting in fast loading speeds.',
  },
  {
    id: 2,
    category: 'Roofing',
    industry: 'Roofing',
    tech: ['Next.js', 'TailwindCSS', 'GSAP'],
    overview: 'A high-converting website concept for regional roofing contractors, featuring an interactive estimator and gallery grids showing project progress.',
    challenge: 'Aesthetic trust is critical for roofing services. Outdated websites lead to higher bounce rates. The contractor required a modern showcase of project case studies.',
    solution: 'We created custom project pages with before-and-after galleries, interactive estimation tools, and structured local search optimizations.',
    outcome: 'Delivered a clean interface that highlights project case studies and makes it easy for clients to request estimates.',
  },
  {
    id: 3,
    category: 'Landscaping',
    industry: 'Landscaping',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'An elegant portfolio presentation for estate landscaping architects, featuring clean layouts, smooth scroll effects, and visual galleries.',
    challenge: 'High-end estate services require a premium visual presentation to match client expectations. Template sites fail to convey luxury craftsmanship.',
    solution: 'We designed a minimal portfolio layout with high-resolution image galleries and subtle scroll-triggered transitions.',
    outcome: 'An elegant showcase that highlights project craftsmanship and matches high-end client expectations.',
  },
  {
    id: 4,
    category: 'HVAC',
    industry: 'HVAC',
    tech: ['React.js', 'Node.js', 'TailwindCSS'],
    overview: 'An emergency service routing website concept for commercial HVAC providers. Features service-area schema integrations to prioritize emergency inquiries.',
    challenge: 'HVAC inquiries are often urgent. The site structure needs to help users find contact information and service availability immediately.',
    solution: 'We built a conversion-focused interface highlighting response times, active coverage areas, and simple contact forms.',
    outcome: 'An optimized layout that helps users quickly find contact details and request urgent services.',
  },
  {
    id: 5,
    category: 'Interior Design',
    industry: 'Interior Design',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'A premium showcase layout for high-end interior design firms, featuring clean typography and minimal product grids.',
    challenge: 'Interior design websites must reflect the style and quality of the projects they showcase. Spaced layouts are essential.',
    solution: 'We designed a minimal gallery layout with detailed project case studies and high-resolution visuals.',
    outcome: 'A premium showcase that emphasizes high-resolution imagery and project craftsmanship.',
  },
  {
    id: 6,
    category: 'Law Firm',
    industry: 'Law Firm',
    tech: ['React.js', 'Vite', 'TailwindCSS'],
    overview: 'A secure, professional portal concept for corporate law practices. Features simple scheduling and practice area resource grids.',
    challenge: 'Legal services require a presentation that builds immediate trust and authority, while ensuring practice details are easy to find.',
    solution: 'We built a secure client portal with team bio pages, consultation schedulers, and clear practice summaries.',
    outcome: 'A clean, professional interface that conveys trust and simplifies initial client consultations.',
  },
  {
    id: 7,
    category: 'Dental',
    industry: 'Dental',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'A patient onboarding portal concept for boutique dental clinics. Features online scheduling, intake forms, and service guides.',
    challenge: 'Dental patient acquisition relies on a smooth onboarding process. Outdated registration steps lead to dropped bookings.',
    solution: 'We created an integrated registration flow with digital intake forms and clear service guides.',
    outcome: 'A clean, modern onboarding interface that helps patients book visits and complete forms online.',
  },
  {
    id: 8,
    category: 'Restaurant',
    industry: 'Restaurant',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'A high-end dining menu and reservations concept, featuring interactive menus and smooth navigation.',
    challenge: 'Fine dining relies on visual storytelling. Online menus need to be highly readable across mobile and desktop screens.',
    solution: 'We developed an interactive digital menu with clear layouts and online reservation integrations.',
    outcome: 'A responsive digital menu that adapts to mobile screens and supports online reservations.',
  },
  {
    id: 9,
    category: 'Construction',
    industry: 'Construction',
    tech: ['React.js', 'TailwindCSS', 'Framer Motion'],
    overview: 'A case-study portal concept for commercial builders, featuring project galleries and safety documentation grids.',
    challenge: 'Commercial construction bids depend on demonstrating past project performance and safety compliance.',
    solution: 'We designed a project portal showcasing safety records, contract milestones, and high-fidelity project galleries.',
    outcome: 'A clean portfolio presentation that highlights construction safety records and project scope.',
  },
];

export const PRICING_PLANS = [
  {
    name: 'Starter',
    description: 'Perfect for local brands seeking a professional, high-performing digital foundation.',
    features: [
      'Custom React framework build (Vite)',
      'Up to 6 high-fidelity pages',
      'Mobile-responsive layout optimizations',
      'Basic Local SEO schemas',
      'Secure contact & lead acquisition',
      'Instant load speed optimization',
      '30-day post-launch support & warranty',
    ],
    highlighted: false,
  },
  {
    name: 'Business',
    description: 'Designed for scaling companies needing custom features and search visibility.',
    features: [
      'Custom React framework build (Vite)',
      'Up to 15 optimized pages',
      'Figma visual design asset kit',
      'Google Business Profile optimization',
      'Dynamic blog and content system setup',
      'JSON-LD structured schema maps',
      'API integrations & calendar setups',
      '60-day post-launch support & warranty',
    ],
    highlighted: true,
  },
  {
    name: 'Enterprise',
    description: 'Complete digital solutions for established companies requiring custom features and ongoing audits.',
    features: [
      'Unlimited custom page routing',
      'Premium custom user experience design',
      'Comprehensive Local & Technical SEO setup',
      'Database planning & dashboard creation',
      'Custom database API endpoints',
      'Google profile reinstatement support',
      '90-day post-launch support & warranty',
      'Priority support response terms',
    ],
    highlighted: false,
  },
];

export const FAQ_DATA = [
  {
    question: 'How long does a website take to build?',
    answer: 'A standard professional business website typically takes 3 to 6 weeks from the initial discovery call to launch. Custom enterprise platforms requiring database integration or complex custom APIs may take longer. We outline clear timelines in our project agreements.',
  },
  {
    question: 'Do you provide SEO services?',
    answer: 'Yes, we provide comprehensive Local and Technical SEO services. Every website we build includes clean semantic HTML code, schema tags, fast loading speeds, and responsive layouts to support search engine rankings.',
  },
  {
    question: 'Do you redesign websites?',
    answer: 'Yes, we specialize in redesigning outdated websites to improve performance and user experience while preserving your existing search traffic and setting up redirects.',
  },
  {
    question: 'Do you develop mobile apps?',
    answer: 'Yes, we build native and cross-platform mobile apps for iOS and Android, focusing on fast performance and clean, premium interfaces.',
  },
  {
    question: 'Can you recover suspended Google Business Profiles?',
    answer: 'Yes, we assist with Google Business Profile reinstatement. If your listing has been suspended, we analyze the cause, ensure compliance with policies, and manage the appeal process.',
  },
  {
    question: 'Do you provide maintenance?',
    answer: 'Yes, we offer monthly maintenance plans covering plugin upgrades, daily backups, security monitoring, and content updates.',
  },
  {
    question: 'How does payment work?',
    answer: 'Our payment milestones are straightforward: 30% of the project cost is due before work begins, and the remaining 70% is due after the website is completed, approved by you, and deployed to your live domain.',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Operations Officer',
    company: 'Capital Investments Group',
    text: 'Zenith redesigned our company portal. The design is clean, the loading speed is sub-second, and their team was clear and professional throughout the project.',
    rating: 5,
  },
  {
    name: 'Marketing Lead',
    company: 'Prime Developers',
    text: 'Their technical SEO optimization helped improve our regional search rankings, and the clean design has helped us attract more qualified client inquiries.',
    rating: 5,
  },
  {
    name: 'Managing Director',
    company: 'Boutique Architecture Firm',
    text: 'The web design is clean and responsive. Our clients have commented on the updated presentation of our portfolio galleries.',
    rating: 5,
  },
];
